### ISSUE TITLE
Invisible Giants

### ISSUE THREAD

**Issue by majinvegetal666** [MonAmiral/GiantChibi#1]
Giants turn invisible while using this mod. Pertinent error here.
From BepInEx:

[Error  : Unity Log] ArgumentException: The Object you want to instantiate is null.
Stack trace:
UnityEngine.Object.Instantiate (UnityEngine.Object original, UnityEngine.Transform parent, System.Boolean instantiateInWorldSpace) (at <e27997765c1848b09d8073e5d642717a>:0)
UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Transform parent, System.Boolean worldPositionStays) (at <e27997765c1848b09d8073e5d642717a>:0)
UnityEngine.Object.Instantiate[T] (T original, UnityEngine.Transform parent) (at <e27997765c1848b09d8073e5d642717a>:0)
GiantChibi.ChibiModel.Start () (at <9d83c97ddb7b48c59539d8ee8719c762>:0)

Using BepInExPack, LC_API.

**Comment by MonAmiral** [comment]
Ah, LC_API 3.0.0 broke everything despite saying it wouldn't, I'll fix it. Thank you for the report!

**Comment by MonAmiral** [comment]
Version 1.0.1 now works properly!
